source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

inhibit_all_warnings!


target 'SwiftDemo' do
  # Use dynamic frameworks
  use_frameworks!

  # 网络请求，类似`AFNetworking`
  # https://github.com/Alamofire/Alamofire
  pod 'Alamofire', '~> 5.1.0'
  
  # JOSN转模型
  # https://github.com/SwiftyJSON/SwiftyJSON
  pod 'SwiftyJSON', '~> 5.0.0'
  # https://github.com/alibaba/handyjson
  pod 'HandyJSON', '~> 5.0.1'
  
  # 自动布局类似`Masonry`
  # https://github.com/SnapKit/SnapKit
  pod 'SnapKit', '~> 5.0.1'
  
  
  target 'SwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
